# Zielsetzung {.unlisted .unnumbered}

Raum ist politisch — das ist im Bezug auf Stadt besonders offensichtlich. Die Stadt ist aber auch ein exzellentes Beispiel, und den Zusammenhang von Raum und Macht grundsätzlicher zu verstehen. In dem theoretisch orientierten Seminar vertiefen wir gemeinsam unser Verständnis der Politischen Geographie am Beispiel des Städtischen. Ziel ist es, Begriffe und Ansätze für die eigene kritische Perspektive auf Stadtentwicklung und städtische Prozesse zu schärfen. Die Politische Geographie bietet hier vor allem einen Ausgangspunkt, das Verhältnis von Stadt, Raum und Macht jenseits von Stadtpolitik und Verwaltung im engeren Sinn wahrzunehmen.

1. **Stadt -- Gesellschaft**
   Zum einen ist die Stadt eine privilegierte Arena für gesellschaftliche Machtverhältnisse und zugleich für Emanzipation und Widerstand. Beispielsweise hat der Zugriff auf ‚lebenswerte‘ städtische Räume wachsende Bedeutung in einer zunehmend auf kognitiv-kulturelle Wertschöpfung orientierten Ökonomie (Scott 2014; Rossi and Di Bella 2017). Dadurch bekommen die Konflikte um städtische Räume eine neue Brisanz (Mayer 2014). Teils wird das ‚Right to the City‘ als der zentrale strategischer Angriffspunkt sozialer Bewegungen gegen herrschende Verhältnisse propagiert (Harvey 2012). Worin liegen Potentiale und Grenzen einer solchen, von gesellschaftlichen Strukturen her argumentierenden Stadtforschung?

2. **Stadt -- Assemblage**
   Ein ganz anderer Vorschlag geht dahin, die Relationen und Verschränkungen von Menschen und Nicht-menschlichem für ein Verständnis des Politischen stärker in Rechnung zu stellen Eine solche relationale Ontologie wird als ein vielversprechender Ausgangspunkt gerade auch in der Stadtforschung diskutiert (Färber 2014; McFarlane 2011). Welche neuen Perspektiven eröffnet der Urban Assemblage Ansatz? Was gerät aus dem Blick?

3. **Stadt -- Epistemologie**
   Neben einer Auseinandersetzung mit der politischen Relevanz des Städtischen bedeutet eine machtsensible Perspektive zum zweiten auch eine Auseinandersetzung mit der Stadtforschung selbst und ihren Konzepten. Vor allem aus einer postkolonialen Perspektive werden zuletzt die Scheuklappen aber auch die eurozentrische Tendenz einer universalisierenden Perspektive auf Stadt nach westlichem Muster betont (Robinson 2006). Kann es angesichts dieser Kritik noch eine allgemeine Theorie der Stadt geben? Wie lässt sich eine Stadtforschung betreiben, die übergreifende Machtwirkungen nicht ignoriert ohne zu universalisieren (Hörning 2018)? Was lässt sich aus der politischen Geographie für eine reflektierte kritische Stadtforschung lernen?

Das Vertiefungsseminar bedeutet in der Hauptsache Lektüre und Auseinandersetzung mit Texten. Ziel ist es, Orientierung über zentrale Debatten zu bekommen, wichtige Begriffe und Ansätze zu verstehen und exemplarische Anwendungen zu diskutieren. Die Diskussion der Texte wird zentral über schriftliche Ausarbeitungen organisiert. Anhand von Lektüreimpulsen erstellen sie jede Woche einen kurzen Kommentar zu der Pflichtlektüre. Zu jedem Thema wir es einen ergänzenden Input geben, der Hintergründe oder wichtiges zusätzliches Material beibringt.

### Literatur zum Einstieg {.unlisted .unnumbered}
* Stadt - Gesellschaft: Harvey, David. 2013. *Rebellische Städte. Vom Recht auf Stadt zur urbanen Revolution*. Berlin: Suhrkamp.
* Stadt - Assemblage: McFarlane, Colin. 2011. Assemblage and critical urbanism. *City* 15, Nr. 2: 204–224.
* Stadt - Epistemologie: Roy, Ananya. 2009. The 21st-Century Metropolis: New Geographies of Theory. *Regional Studies* 43, Nr. 6: 819–830.
