# Anforderungen {-}

Als Vertiefungsseminar steht die Auseinandersetzung mit der relevanten Literatur im Zentrum. Zentrale Leistungsanforderung ist daher die regelmäßige Lektüre. Daneben ist als mündliche Leistung in einer Seminarsitzung ein mündliches Referat vorgesehen.

## Überblick Leistungsanforderungen {-}

1. **Pflichtlektüre**
  Zu jeder Sitzung ist ein Text angegeben (ca. 20 - 40 Seiten). Der Text ist verpflichtend von allen zu lesen und stellt die Grundlage für die Diskussion im Seminar dar.

2. **Lektüreimpuls und Kommentar**
   Zur Pflichtlektüre ist jeweils ein Lektüreimpuls angegeben. Das sind zumeist zentrale Zitate oder Begriffe aus dem jeweiligen Text. Jede/r Teilnehmer:in formuliert für jede Woche eine kurze Antwort auf diesen Impuls. Die Antworten werden über Moodle ausgetauscht und gegenseitig kommentiert. Diese Auseinandersetzung im Vorfeld informiert und strukturiert die Diskussion im Seminar.

3. **Kurzreferat**
   Zu jeder Sitzung ist ein weiterführender Text angegeben. Die Lektüre ist empfohlen aber optional. Zu einer Sitzung bereitet jede/r Teilnehmer*in einen kurzen Input vor, der auf diesem zusätzlichen Text basiert und ggf. weitere eigene Recherche zum Thema umfasst.

4. **Modulabschlussprüfung**
   Das Modul wird mit einer Prüfung in Form einer wissenschaftlichen Hausarbeit abgeschlossen. In der Hausarbeit wird eine Aspekt der Diskussion im Seminar aufgegriffen und unter Einbezug von weiterer Literatur vertieft (25.000 - 30.000 Zeichen).

\pagebreak
