# Stadt als soziomaterielles Gefüge

Eine weitere Perspektive nimmt das Städtische ebenfalls als einen prädestinierten Fall für eine kritische Auseinandersetzung mit Gesellschaft, allerdings hier dezidiert nicht als Anwendungsfall feststehender Hypothesen sondern als Ansatzpunkt für das empirische Aufdecken sozio-materieller Ko-Produktion. Die Stadt erlaubt ein präzises Verständnis der Ko-Produktion sozialer Realität, so die Erwartung.

## Sitzung am 31.05. - ANT in der Stadtforschung?

Die Grundidee hier ist die fruchtbare Anwendung theoretischer Erkenntnisse aus den _Science and Technology Studies_ für die kritische Stadtforschung. In der ersten Sitzung des Blocks setzen wir uns mit einem solchen Plädoyer auseinander [@Farias16Introducing]. Das Referat vertieft das Verständnis von ANT auf Basis eines frühen klärenden Einwurfs von John Law [@Law99After-AN].

### Pflichtlektüre {.unlisted .unnumbered}

- Farías, Ignacio und Anders Blok. 2016. Introducing Urban Cosmopolitics. In: *Urban Cosmopolitics*, hg. von Anders Blok und Ignacio Farías, 1--18. London: Routledge.

### Referat {.unlisted .unnumbered}

- Law, John. 1999. After ANT: complexity, naming and topology. *Sociological Review* 47, Nr. 1: 1--14.

## Sitzung am 07.06. -- Hintergrund: Assemblage Urbanism Debatte

Der Text von Farías und Blok aus der Sitzung vom 31.05 [@Farias16Introducing] nimmt unter anderem Bezug auf eine in der englischsprachigen Geographie bereits zuvor und über ein gutes Dutzend Beiträge geführte Debatte. In der zweiten Sitzung des Blocks gehen wir auf diese Debatte partiell ein. Wir beschäftigen uns mit einem kritischen Einwurf [@Brenner11Assemblage] und der Replik darauf [@McFarlane11On-conte].  

### Pflichtlektüre {.unlisted .unnumbered}

- Brenner, Neil, David J. Madden und David Wachsmuth. 2011. Assemblage urbanism and the challenges of critical urban theory. *City* 15, Nr. 2: 225--240.

### Referat {.unlisted .unnumbered}

- McFarlane, Colin. 2011. On context. *City* 15, Nr. 3-4: 375--388. doi:[10.1080/13604813.2011.595111](https://doi.org/10.1080/13604813.2011.595111).

## Sitzung am 14.06. -- Fallbeispiele

Was kann der konkrete Gewinn sein, Stadt als Erscheinungsort der Ko-Produktion sozialer Realität zu begreifen? Wir beschäftigen uns mit zwei aktuellen Anwendungsbeispielen: einem neuen Begriff von städtischer Teilhabe entlang des Zugangs zur Wasser-Infrastruktur [@Anand11PRESSURE] und einem Verständnis von Hochwasserschutz als Assemblage [@Ranganathan15Storm-Dr].

### Pflichtlektüre {.unlisted .unnumbered}

- Anand, Nikhil. 2011. PRESSURE: The PoliTechnics of Water Supply in Mumbai. *Cultural Anthropology* 26, Nr. 4: 542--564.

### Referat {.unlisted .unnumbered}

- Ranganathan, Malini. 2015. Storm Drains as Assemblages: The Political Ecology of Flood Risk in Post-Colonial Bangalore. *Antipode* 47, Nr. 5: 1300--1320. doi:[10.1111/anti.12149](https://doi.org/10.1111/anti.12149).

## Sitzung am 21.06. -- Politische Konsequenzen II - Ethnographisch Städte bauen

Was bedeutet diese Vorschläge für praktische politische Intervention. Ignacio Farías fasst dies unter der Parole „ethnographisch Städte bauen“ [@Farias20Fur-eine]. Wir diskutieren diesen Vorschlag. Das Referat bringt eine klassische Übertragung der Perspektive eines ‚vitalen Materialismus‘ für die Politikwissenschaft zur Diskussion [@Bennett05The-Agen].

### Pflichtlektüre {.unlisted .unnumbered}

- Farías, Ignacio. 2020. Für eine Anthropologie des Urbanismus. Ethnographisch Städte bauen. *Zeitschrift für Volkskunde* 116, Nr. 2: 171--192. doi:[10.31244/zfvk/2020/02.01](https://doi.org/10.31244/zfvk/2020/02.01).

### Referat {.unlisted .unnumbered}

- Bennett, Jane. 2005. The Agency of Assemblages and the North American Blackout. *Public Culture* 17, Nr. 3 (September): 445--466. doi:[10.1215/08992363-17-3-445](https://doi.org/10.1215/08992363-17-3-445).

\pagebreak